name: GriefPreventionFlags
main: me.ryanhamshire.GPFlags.GPFlags
depend: [GriefPrevention]
softdepend: [mcMMO]
authors: [Big_Scary, ShaneBee, DmitryRendov, DrBot]
description: GriefPrevention add-on to set flags in claims.
website: https://www.spigotmc.org/resources/griefprevention-flags.55773/
version: '${project.version}'
api-version: '1.13'
commands:
   gpflags:
      description: Base command for GriefPreventionFlags
permissions:
    gpflags.admin.*:
        description: Grants all administrative functionality.
        children:
            gpflags.setflag: true
            gpflags.defaultflags: true
            gpflags.unsetflag: true
            gpflags.setworldflag: true
            gpflags.unsetworldflag: true
            gpflags.setserverflag: true
            gpflags.unsetserverflag: true
            gpflags.listflags: true
            gpflags.reload: true
            gpflags.allflags: true
            gpflags.bypass: true
            gpflags.bypass.fly: true
    gpflags.setflag:
        description: Grants permission to use /SetClaimFlag.
        default: op
    gpflags.unsetflag:
        description: Grants permission to use /UnSetClaimFlag.
        default: op
    gpflags.setworldflag:
        description: Grants permission to use /SetWorldFlag.
        default: op
    gpflags.unsetworldflag:
        description: Grants permission to use /UnSetWorldFlag.
        default: op
    gpflags.setserverflag:
        description: Grants permission to use /SetServerFlag.
        default: op
    gpflags.unsetserverflag:
        description: Grants permission to use /UnSetServerFlag.
        default: op
    gpflags.defaultflags:
        description: Grants permission to use /SetDefaultClaimFlag and /UnSetDefaultClaimFlag.
        default: op
    gpflags.listflags:
        description: Grants permission to use /ListClaimFlags.
        default: op
    gpflags.reload:
        description: Grants permission to use /GPFReload.
        default: op
    gpflags.allflags:
        description: Grants permission to apply/remove all flags.
        default: op
    gpflags.bypass:
        description: Makes a player immune to the limitations of flags like CommandBlackList, NoEnter, and NoFlight.
        default: op
        children:
            gpflags.bypass.fly: true
    gpflags.bypass.fly:
        description: Makes a player immune to the limitations of the ownerfly and ownermemberfly flags
        default: op
    gpflags.bypass.nofly:
        description: Makes a player immune to the limitations of the nofly flag
        default: op
    gpflags.bypass.exitcommand:
        description: Makes a player immune to the exit command flag
        default: op
    gpflags.bypass.entercommand:
      description: Makes a player immune to the enter command flag
      default: op
